#!/bin/bash

# ------------------------------------------------------------------------------
# | Navigation                                                                 |
# ------------------------------------------------------------------------------

alias ~="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias cd..="cd .."

# ------------------------------------------------------------------------------
# | Network                                                                    |
# ------------------------------------------------------------------------------

alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

if [[ "$os" == "linux" && "$distro" == "ubuntu" ]]; then
    alias localip="ifconfig | \
                   grep 'inet addr' | \
                   grep -v '127.0.0.1' | \
                   cut -d: -f2 | \
                   cut -d' ' -f1"
elif [ "$os" == "mac" ]; then
    alias localip="ipconfig getifaddr en1"
fi

# ------------------------------------------------------------------------------
# | Package Managers                                                           |
# ------------------------------------------------------------------------------

# Node Package Manager
alias npmi="npm install"
alias npmr="npm uninstall"
alias npms="npm search"
alias npmu="npm update"

if [[ "$os" == "linux" && "$distro" == "ubuntu" ]]; then

    # Advanced Packaging Tool
    alias apti="sudo apt-get install"
    alias aptr="sudo apt-get remove"
    alias apts="sudo apt-cache search"
    alias aptu="sudo apt-get update && \
                sudo apt-get upgrade"

    alias update="aptu && npmu"

elif [ "$os" == "mac" ]; then

    # Homebrew
    alias brewi="brew install"
    alias brewr="brew uninstall"
    alias brews="brew search"
    alias brewu="brew update &&  \
                 brew upgrade && \
                 brew cleanup"

    alias update="sudo softwareupdate --install --all && \
                  brewu && \
                  npmu"

fi

# ------------------------------------------------------------------------------
# | Shorter Commands                                                           |
# ------------------------------------------------------------------------------

alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim"
alias g="git"
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"
alias q="exit"
alias :q="exit"
alias rm="rm -rf"

# OS / OS distribution specific commands
if [[ "$os" == "linux" && "$distro" == "ubuntu" ]]; then

    # Hide/Show desktop icons
    alias hidedesktopicons="gsettings set org.gnome.desktop.background show-desktop-icons false"
    alias showdesktopicons="gsettings set org.gnome.desktop.background show-desktop-icons true"

    # Restart Apache
    alias ra="sudo /etc/init.d/apache2 restart"

elif [ "$os" == "mac" ]; then

    # Empty the trash, the main HDD and on all mounted volumes
    # and clear Apple’s system logs to improve shell startup speed
    alias emptytrash="sudo rm -frv /Volumes/*/.Trashes && \
                      sudo rm -frv ~/.Trash &&
                      sudo rm -frv /private/var/log/asl/*.asl"

    # Hide/Show desktop icons
    alias hidedesktopicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
    alias showdesktopicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

    # Hide/Show hidden files in Finder
    alias hidehiddenfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
    alias showhiddenfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"

    # Restart Apache
    alias ra="sudo apachectl restart"

fi

# ------------------------------------------------------------------------------
# | Other                                                                      |
# ------------------------------------------------------------------------------

alias nyancat="telnet miku.acm.uiuc.edu"
alias starwars="telnet towel.blinkenlights.nl"
