#!/bin/bash

declare DOTFILES_DIR_PATH="$(dirname $(dirname $(readlink $BASH_SOURCE)))"

source "$DOTFILES_DIR_PATH/os/utils.sh" \
    && declare OS="$(get_os)"

# ----------------------------------------------------------------------

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cd..='cd ..'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q='exit'
alias c='clear'
alias ch='history -c && > ~/.bash_history'
alias e='vim'
alias g='git'
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias ll='ls -l'
alias m='man'
alias map='xargs -n1'
alias n='npm'
alias q='exit'
alias rm='rm -rf'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases

if [ "$OS" == 'osx' ]; then
    source "$DOTFILES_DIR_PATH/shell/os_x/bash_aliases"
elif [ "$OS" == 'ubuntu' ]; then
    source "$DOTFILES_DIR_PATH/shell/ubuntu/bash_aliases"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup

unset DOTFILES_DIR_PATH
unset OS
