#!/bin/bash

check_linux_release() {
    [ -e "/etc/$1" ] && printf "%s" "$2"
}

load_dotfiles() {

    local distro="" i="" os="" tmp=""
    local osname="$(uname -s)"

    declare -a files=(
        "bash_aliases"
        "bash_exports"
        "bash_functions"
        "bash_options"
        "bash_prompt"
        "bash.local"    # for local settings that should
                        # not be under version control
    )

    if [[ $COLORTERM == gnome-* && $TERM == xterm ]] \
       && infocmp gnome-256color >/dev/null 2>&1; then
        export TERM=gnome-256color
    elif infocmp xterm-256color >/dev/null 2>&1; then
        export TERM=xterm-256color
    fi

    # Some things are OS specific, deal with it
    if [ "$osname" == "Darwin" ]; then
        os="osx"
    elif [ "$osname" == "Linux" ]; then
        os="linux"

        # Get Linux distribution
        # (list of release: http://linuxmafia.com/faq/Admin/release-files.html)
        distro=$(check_linux_release "lsb-release" "ubuntu") ||
               $(check_linux_release "debian_version" "debian") ||
               $(check_linux_release "debian_release" "debian")
    else
        os="other"
    fi

    for i in ${!files[*]}; do
        tmp="$HOME/.${files[$i]}"
        [ -r "$tmp" ] && source "$tmp"
    done

    # Enable programmable completion features
    if [ "$os" == "osx" ]; then
        if [ -f $(brew --prefix)/etc/bash_completion ]; then

            . $(brew --prefix)/etc/bash_completion

            # Make bash complete the `g` alias, just like it does `git`
            complete -o default -o nospace -F _git g
        fi
    else
        if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
            . /etc/bash_completion
        fi
    fi

}

# ##############################################################################
# # MAIN                                                                       #
# ##############################################################################

load_dotfiles
unset load_dotfiles
unset check_linux_release

# Clear system messages (e.g.: system copyright notice, the
# date and time of the last login, the message of the day, etc.)
clear
