#!/bin/bash

load_dotfiles() {

    local i="" os="" tmp=""
    local osname="$(uname -s)"

    declare -a files=(
        "bash_aliases"
        "bash_exports"
        "bash_functions"
        "bash_options"
        "bash_prompt"
        "bash.local"    # for local settings that should
                        # not be under version control
    )

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && \
       infocmp gnome-256color >/dev/null 2>&1; then
        export TERM=gnome-256color
    elif infocmp xterm-256color >/dev/null 2>&1; then
        export TERM=xterm-256color
    fi

    # Some things are OS specific, deal with it!

    if [ "$osname" == "Darwin" ]; then
        os="osx"

    # Get Linux distribution
    # https://web.archive.org/web/20130929034731/http://linuxmafia.com/faq/Admin/release-files.html
    elif [ "$osname" == "Linux" ] &&
         [ -e "/etc/lsb-release" ]; then
        os="ubuntu"
    else
        os="other"
    fi

    for i in ${!files[*]}; do
        tmp="$HOME/.${files[$i]}"
        [ -r "$tmp" ] && source "$tmp"
    done

    # Enable programmable completion features
    if [ "$os" == "osx" ]; then
        if [ -f $(brew --prefix)/etc/bash_completion ]; then

            . $(brew --prefix)/etc/bash_completion

            # Make bash complete the `g` alias, just like it does `git`
            complete -o default -o nospace -F _git g
        fi
    else
        if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
            . /etc/bash_completion
        fi
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

load_dotfiles
unset load_dotfiles

# Clear system messages (e.g.: system copyright notice, the
# date and time of the last login, the message of the day, etc.)
clear
