#!/bin/bash

declare -a FILES_TO_COPY=(
    "git/gitconfig"
)

declare -a FILES_TO_SYMLINK=(
    "shell/bash_aliases"
    "shell/bash_functions"
    "shell/bash_exports"
    "shell/bash_prompt"
    "shell/bash_profile"
    "shell/bash_logout"
    "shell/bashrc"
    "shell/inputrc"

    "git/gitattributes"
    "git/gitignore"

    "vim/vim"
    "vim/vimrc"
    "vim/gvimrc"
)

declare -r GITHUB_REPOSITORY="alrra/dotfiles"

declare -a NEW_DIRECTORIES=(
    "$HOME/archive"
    "$HOME/Downloads/torrents"
    "$HOME/projects"
    "$HOME/server"
)

declare -a NPM_PACKAGES=(
    "jshint"
)

declare dotfiles_directory="$HOME/projects/dotfiles"
declare force=1 # values: `0` (true) or `1` (false)
declare os=""

# ######################################################################
# # HELPER FUNCTIONS                                                   #
# ######################################################################

answer_is_yes() {
    [[ "$REPLY" =~ ^[Yy]$ ]] && return 0 || return 1
}

ask() {
    print_question "$1"
    read
}

ask_for_confirmation() {
    print_question "$1 (y/n) "
    read -n 1
    printf "\n"
}

ask_for_confirmation_if_needed() {
    [ $force -eq 1 ] && ask_for_confirmation "$1"

    if [ $force -eq 0 ] || \
       [ $(answer_is_yes; printf $?) -eq 0 ]; then
        return 0
    fi

    return 1
}

ask_for_sudo() {

    # Ask for the administrator password upfront
    sudo -v

    # Update existing `sudo` time stamp until this script has finished
    # https://gist.github.com/cowboy/3118588
    while true; do
        sudo -n true
        sleep 60
        kill -0 "$$" || exit
    done &> /dev/null &
}

check_github_ssh_key() {

    declare -r GITHUB_SSH_URL="https://github.com/settings/ssh"
    local ssh_key_file="id_rsa.pub"

    if [ "$(ssh -T git@github.com &> /dev/null; printf $?)" -ne 1 ]; then

        cd "$HOME/.ssh"

        # Setup GitHub SSH Key
        # https://help.github.com/articles/generating-ssh-keys

        print_info "Set up the SSH key"

        if [ ! -r "$ssh_key_file" ]; then
            rm -rf "$ssh_key_file"
            ask "Please provide an email address (email): " && printf "\n"
            ssh-keygen -t rsa -C "$(get_answer)"
        fi

        if [ "$os" == "osx" ]; then

            # Copy SSH key to clipboard
            cat "$ssh_key_file" | pbcopy
            print_result $? "Copy SSH key to clipboard"

            # Open the GitHub web page where the SSH key can be added
            open "$GITHUB_SSH_URL"

        elif [ "$os" == "ubuntu" ]; then

            # Copy SSH key to clipboard
            cat "$ssh_key_file" | xclip -selection clip
            print_result $? "Copy SSH key to clipboard"

            # Open the GitHub web page where the SSH key can be added
            xdg-open "$GITHUB_SSH_URL"

        fi

        # Before proceeding, wait for everything to be ok
        while [ "$(ssh -T git@github.com &> /dev/null; printf $?)" -ne 1 ]; do
            sleep 5;
        done

        print_success "Set up the SSH key"
    fi
}

check_os() {

    # Check if the OS is OS X and it is above a certain version
    if [ "$(uname -s)" = "Darwin" ]; then
        if [ $(compare_versions "$(sw_vers -productVersion)" "10.10") == '<' ]; then
            print_error "Sorry, this script is intended only for OS X 10.10.0+."
            return 1
        else
            os="osx"
            return 0
        fi

    # Check if the OS is Ubuntu
    else
        if [ "$(uname -s)" != "Linux" ] || [ ! -e "/etc/lsb-release" ]; then
            print_error "Sorry, this script is intended only for OS X and Ubuntu!"
            return 1
        else
            os="ubuntu"
            return 0
        fi
    fi

}

cmd_exists() {
    [ -x "$(command -v "$1")" ] \
        && printf 0 \
        || printf 1
}

compare_versions() {

    declare -a v1=(${1//./ })
    declare -a v2=(${2//./ })
    local i=""

    # Fill empty positions in v1 with zeros
    for (( i=${#v1[@]}; i<${#v2[@]}; i++ )); do
        v1[i]=0
    done

    for (( i=0; i<${#v1[@]}; i++ )); do
        # Fill empty positions in v2 with zeros
        if [[ -z ${v2[i]} ]]; then
            v2[i]=0
        fi

        if (( 10#${v1[i]} > 10#${v2[i]} )); then
            printf ">"
            return 0;
        fi

        if (( 10#${v1[i]} < 10#${v2[i]} )); then
            printf "<"
            return 0;
        fi
    done

    printf "="
}

copy_files() {
    print_info "Copy files"
    place_files "cp -f" "${FILES_TO_COPY[@]}"
}

create_directories() {
    print_info "Create directories"
    ask_for_confirmation_if_needed "Do you want the additional directories to be created?"
    if [ $? -eq 0 ]; then
        [ $force -eq 1 ] && printf "\n"
        for i in ${NEW_DIRECTORIES[@]}; do
            mkd "$i"
        done
    fi
}

create_symbolic_links() {
    print_info "Create symbolic links"
    place_files "ln -fs" "${FILES_TO_SYMLINK[@]}"
}

download_and_extract_archive() {

    local tmpFile="$(mktemp -u XXXXX)"

    print_info "Download and extract archive"

    cd '/tmp'

    # Download archive
    if [ "$os" == "osx" ]; then

        curl -LsSo "$tmpFile" "$1"
        #     │││└─ write output to file
        #     ││└─ show error messages
        #     │└─ don't show the progress meter
        #     └─ follow redirects

    elif [ "$os" == "ubuntu" ]; then

        wget -qO "$tmpFile" "$1"
        #     │└─ write output to file
        #     └─ don't show output

    fi

    print_result $? "Download archive" "true"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    ask_for_confirmation "Do you want to store the dotfiles in '$dotfiles_directory'?"
    if ! answer_is_yes; then
        ask "Please specify another location for the dotfiles (path):"
        dotfiles_directory="$(get_answer)"
    fi

    # Ensure the `dotfiles` directory is available
    if [ -e "$dotfiles_directory" ]; then
        while [ -e "$dotfiles_directory" ]; do

            ask_for_confirmation "'$dotfiles_directory' already exists! Do you want to overwrite it?"

            if answer_is_yes; then
                rm -rf "$dotfiles_directory"
                break
            else
                ask "Please specify another location for the dotfiles (path)"
                dotfiles_directory="$(get_answer)"
            fi
        done
    fi

    mkd "$dotfiles_directory"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Extract archive to the `dotfiles` directory
    tar -zxf "$tmpFile" --strip-components 1 -C "$dotfiles_directory"
    print_result $? "Extract archive" "true"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Remove the archive
    rm -rf "$tmpFile"
    print_result $? "Remove archive"
}

execute() {
    $1 &> /dev/null
    print_result $? "${2:-$1}"
}

get_answer() {
    printf "$REPLY"
}

git_initialize_repository() {
    print_info "Initialize git repository"
    cd "$dotfiles_directory"
    if ! is_git_repository; then
        git init &> /dev/null \
            && git remote add origin "$1" &> /dev/null
        print_result $? "Initialize the 'dotfiles' git repository"
    fi
}

git_update_content() {
    print_info "Update content"
    cd "$dotfiles_directory"
    if is_git_repository; then

        ask_for_confirmation_if_needed "Do you want to update the content from the 'dotfiles' directory?"

        if [ $? -eq 0 ]; then
            check_github_ssh_key

            cd "$dotfiles_directory"
            [ $force -eq 1 ] && printf "\n"

            # Update content, remove untracked files and fetch submodules
            git fetch --all &> /dev/null \
                && git reset --hard origin/master &> /dev/null \
                && git clean -fd  &> /dev/null \
                && git submodule update --recursive --init --quiet &> /dev/null \

            print_result $? "Update content"
        fi
    fi
}

install_apps() {

    print_info "Install applications"

    if [ "$os" == "osx" ]; then
        source "$dotfiles_directory/os/os_x/install_applications.sh"
    elif [ "$os" == "ubuntu" ]; then
        source "$dotfiles_directory/os/ubuntu/install_applications.sh"
    fi

    ask_for_confirmation_if_needed "Do you want to install the applications/command line tools?"

    if [ $? -eq 0 ]; then

        [ $force -eq 1 ] && printf "\n"
        install_applications

        printf "\n"
        install_npm_packages

    fi
}

install_npm_packages() {

    # Make sure the most recent version of npm is installed
    npm install -q -g npm &> /dev/null
    print_result $? "npm [update]"

    for i in ${NPM_PACKAGES[@]}; do
        execute "npm install -g $i" "$i"
    done
}

is_git_repository() {
    if [ $(git rev-parse --is-inside-work-tree &> /dev/null; printf "%s" $?) == 0 ]; then
        return 0;
    else
        return 1;
    fi
}

mkd() {
    if [ -n "$1" ]; then
        if [ -e "$1" ]; then
            if [ ! -d "$1" ]; then
                print_error "$1 - a file with the same name already exists!"
            else
                print_success "$1"
            fi
        else
            execute "mkdir -p $1" "$1"
        fi
    fi
}

place_file() {
    if [ -e "$3" ]; then
        ask_for_confirmation_if_needed "'$3' already exists! Do you want to overwrite it?"
        if [ $? -eq 0 ]; then
            rm -rf "$3"
            execute "$1 $2 $3" "$3 → $2"
        else
            print_error "$3 → $2"
        fi
    else
        execute "$1 $2 $3" "$3 → $2"
    fi
}

place_files() {
    local cmd=$1
    local sourceFile="", targetFile=""

    shift 1
    declare -a files=("$@")

    for i in ${files[@]}; do
        [ $force -eq 1 ] && [ "$i" != "${files[0]}" ] && printf "\n"
        sourceFile="$dotfiles_directory/$i"
        targetFile=$(printf "%s" "$HOME/.$i" | sed "s/.*\/\(.*\)/\1/g")
        place_file "$cmd" "$sourceFile" "$HOME/.$targetFile"
    done
}

print_error() {
    # Print output in red
    printf "\e[0;31m  [✖] $1 $2\e[0m\n"
}

print_help_message() {
    printf "\n"
    printf "OPTIONS:"
    printf "\n"
    printf "\n"
    printf " -f, --force\n"
    printf "\n"
    printf "     Makes the update/setup process avoid the confirmation prompt\n"
    printf "\n"
}

print_info() {
    # Print output in purple
    printf "\n\e[0;35m $1\e[0m\n\n"
}

print_result() {
    [ $1 -eq 0 ] \
        && print_success "$2" \
        || print_error "$2"

    [ "$3" == "true" ] && [ $1 -ne 0 ] \
        && exit
}

print_success() {
    # Print output in green
    printf "\e[0;32m  [✔] $1\e[0m\n"
}

print_question() {
    # Print output in yellow
    printf "\e[0;33m  [?] $1\e[0m"
}

restart_computer() {

    print_info "Restart"
    ask_for_confirmation "Do you want to restart?"

    if answer_is_yes; then
        print_info "Restarting..."
        sudo shutdown -r now
    fi
}

set_custom_preferences() {

    print_info "Set preferences"

    if [ "$os" == "osx" ]; then
        source "$dotfiles_directory/os/os_x/set_preferences.sh"
    elif [ "$os" == "ubuntu" ]; then
        source "$dotfiles_directory/os/ubuntu/set_preferences.sh"
    fi

    ask_for_confirmation_if_needed "Do you want to set the custom preferences?"

    if [ $? -eq 0 ]; then
        [ $force -eq 1 ] && printf "\n"
        set_preferences
    fi
}

# ######################################################################
# # MAIN                                                               #
# ######################################################################

main() {

    # Ensure the OS is OS X or Ubuntu
    check_os || exit;

    # Handle command-line arguments (options)
    # http://mywiki.wooledge.org/BashFAQ/035
    while :; do
        case $1 in

            -h|-\?|--help)
                print_help_message
                exit
            ;;

            -f|--force)
                force=0
                if [ "$2" ]; then
                    shift 2
                    continue
                fi
            ;;

            -?*) printf 'WARNING: Unknown option (ignored): %s\n' "$1" >&2;;
              *) break;;
        esac

        shift
    done

    # Ensure that the following actions are made
    # relative to the dotfiles directory root
    # http://mywiki.wooledge.org/BashFAQ/028
    cd "${BASH_SOURCE%/*}"

    ask_for_sudo

    # Determine if the `dotfiles` need to be set up or updated
    if [ $(cmd_exists "git") -eq 0 ] && \
       [[ "$(git config --get remote.origin.url)" =~ $GITHUB_REPOSITORY ]]; then

        dotfiles_directory="$(pwd)"
        git_update_content

    else
        download_and_extract_archive "http://github.com/$GITHUB_REPOSITORY/tarball/master"
        git_initialize_repository "git@github.com:$GITHUB_REPOSITORY.git"

    fi

    create_directories
    copy_files
    create_symbolic_links
    install_apps
    set_custom_preferences
    restart_computer
    printf "\n"
}

main "$@"
