" ----------------------------------------------------------------------
" | General Settings                                                   |
" ----------------------------------------------------------------------

set guicursor=n:blinkon0  " Turn off blinking cursor in normal mode

set visualbell            " ┐ Disable beeping and window flashing
set t_vb=                 " ┘ https://vim.wikia.com/wiki/Disable_beeping

" MacVim specific settings
if has('gui_macvim')
    set guifont=Menlo:h15     " Use custom font settings
endif


" ----------------------------------------------------------------------
" | Local Settings                                                     |
" ----------------------------------------------------------------------

" Load local settings if they exist
if filereadable(glob('~/.gvimrc.local'))
    source ~/.gvimrc.local
endif
