name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: thiagoalessio/vader-vim
    steps:
    - uses: actions/checkout@v1
    - name: Running tests with code coverage
      run: |
        cat > ~/.vimrc <<VIMRC
        filetype off
        set rtp+=/vader.vim
        set rtp+=.
        set rtp+=after
        filetype plugin indent on
        VIMRC
        covimerage run vim -c 'Vader! test/*' >/dev/null
    - name: Submitting code coverage report
      run: covimerage xml --omit */default_colors/* && codecov
      env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
