name: Tests

on:
- push
- pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'

    - name: Install dependencies
      run: sudo apt-get -y install vim && pip install covimerage

    - name: Install vader.vim
      run: git clone https://github.com/junegunn/vader.vim.git ./vader.vim

    - name: Configure vim
      run: |
        cat > ~/.vimrc <<VIMRC
        filetype off
        set rtp+=$(pwd)/vader.vim
        set rtp+=.
        set rtp+=after
        filetype plugin indent on
        VIMRC

    - name: Run tests with code coverage
      run: covimerage run vim -c 'Vader! test/*'

    - name: Generate code coverage report
      run: covimerage xml --omit */default_colors/*

    - name: Submit code coverage report
      run: bash <(curl -s https://codecov.io/bash)
