#!/bin/bash

# [!] Do not rename this file to `bash_completion`
#     as it will create an infinite loop!

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi


# TAB COMPLETION 

## If there are multiple matches for completion, Tab should cycle through them
bind 'TAB':menu-complete

## Display a list of the matching files
bind "set show-all-if-ambiguous on"  

## Perform partial completion on the first Tab press,
## only start cycling full results on the second Tab press 
bind "set menu-complete-display-prefix on" 
