---
version: 2

jobs:
  test:
    docker:
      - image: thiagoalessio/vader-vim
    steps:
      - checkout
      - run:
          name: Running tests (with code coverage)
          command: |
            covimerage run vim -Nu <(cat << VIMRC
            filetype off
            set rtp+=/vader.vim
            set rtp+=.
            set rtp+=after
            filetype plugin indent on
            VIMRC
            ) -c 'Vader! test/*' >/dev/null

      - run:
          name: Submiting code coverage report
          command: covimerage xml --omit */default_colors/* && codecov

workflows:
  version: 2
  default:
    jobs:
      - test

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/c261f46cf0dc214cdaf3
