#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files() {

    declare -r CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "bash_aliases"
        "bash_autocomplete"
        "bash_exports"
        "bash_functions"
        "bash_options"
        "bash.local"  # For local settings that should
                      # not be under version control.
    )

    local file=""
    local i=""

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" \
        && . "../os/utils.sh"

    # shellcheck disable=SC2034
    declare -r OS="$(get_os)"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    for i in ${!FILES_TO_SOURCE[*]}; do

        file="$HOME/.${FILES_TO_SOURCE[$i]}"

        [ -r "$file" ] \
            && . "$file"

    done

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$CURRENT_DIRECTORY"

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files
# z beats cd most of the time. `brew install z`
zpath="$(brew --prefix)/etc/profile.d/z.sh"
[[ $- == *i* ]] && [[ -f $zpath ]] && source $zpath

# Setup fzf
# ---------
#if [[ ! "$PATH" = */usr/local/opt/fzf/bin* ]]; then
#  export PATH="$PATH:/usr/local/opt/fzf/bin"
#fi
# Auto-completion
# ---------------
#[[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.bash" 2> /dev/null
# Key bindings
# ------------
#source "/usr/local/opt/fzf/shell/key-bindings.bash"

#[[ $- == *i* ]] && [[ -f "/usr/local/bin/virtualenvwrapper.sh" ]] && source /usr/local/bin/virtualenvwrapper.sh 2> /dev/null
#complete -C '~/.virtualenvs/python3/bin/aws_completer' aws
#workon python3

# Only load Liquid Prompt in interactive shells, not from a script or from scp
[[ $- == *i* ]] && source ~/projects/liquidprompt/liquidprompt

# $PATH set by /etc/paths and /etc/paths.d
export PATH=$PATH:/usr/local/sbin:$HOME/projects/dotfiles/src/bin:/usr/local/anaconda3/bin

unset -f source_bash_files
# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
#PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
#export PATH
