#!/bin/bash

# [!] Do not rename this file to `bash_completion`
#     as it will create an infinite loop!

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

declare DOTFILES_DIR_PATH="$(dirname "$(dirname "$(readlink "${BASH_SOURCE[0]}")")")"

source "$DOTFILES_DIR_PATH/os/utils.sh" \
    && declare os="$(get_os)"

# ----------------------------------------------------------------------

# Enable programmable completion features
# http://tldp.org/LDP/abs/html/tabexpansion.html

if [ "$os" == "macos" ]; then
    source "$DOTFILES_DIR_PATH/shell/macos/bash_autocomplete"
elif [ "$os" == "ubuntu" ]; then
    source "$DOTFILES_DIR_PATH/shell/ubuntu/bash_autocomplete"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup

unset DOTFILES_DIR_PATH
unset os
