#!/bin/bash

# Readline library configuration options.
# http://ss64.com/bash/syntax-inputrc.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# If there are multiple matches for completion,
# make TAB cycle through them.

TAB: menu-complete

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Searching files via partial match.

# ↑
"\e[A":history-search-backward
# ↓
"\e[B":history-search-forward

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Disable beeping and window flashing.

set bell-style none

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use case-insensitive TAB autocompletion.

set completion-ignore-case on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Perform partial completion on the first Tab press, and
# only start cycling full results on the second Tab press.

set menu-complete-display-prefix on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Display a list of the matching files

set show-all-if-ambiguous on
