#!/bin/bash

alias ..="cd .." \
...="cd ../.." \
....="cd ../../.." \
cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit" \
c="clear" \
ch="history -c && > ~/.bash_history" \
e="vim --" \
g="git" \
ip="dig +short myip.opendns.com @resolver1.opendns.com" \
ll="ls -l" \
m="man" \
map="xargs -n1" \
n="npm" \
path='printf "%b\n" "${PATH//:/\\n}"' \
q="exit" \
rm="rm -rf --" \
t="tmux" \
y="yarn"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "aliases/$OS/bash_aliases"
