#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="subl"
alias g="git"
alias gs="git s"
alias gc="git commit"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -l"
alias lll="ls -lola"
alias m="man"
alias map="xargs -n1"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"
alias rm="rm -rf --"
alias t="tmux"

alias n="npm"
alias ni='npm install'
alias nig='sudo npm install -g'
alias np='npm publish'
alias nr='npm run'

alias hdi='hide-desktop-icons'
alias sdi='show-desktop-icons'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "aliases/$OS/bash_aliases"
