#!/bin/bash

if [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then

    # Use `bash-completion` 2.x
    . "$(brew --prefix)/share/bash-completion/bash_completion"

    # Make Bash complete the `g` alias just like it does `git`
    complete -o default -o nospace -F _git g

fi
