#!/bin/bash

# [!] Do not rename this file to `bash_completion`
#     as it will create an infinite loop!

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then

    # Use latest `bash-completion`
    . "$(brew --prefix)/share/bash-completion/bash_completion"

    # Make Bash complete the `g` alias just like it does `git`
    complete -o default -o nospace -F _git g

fi
