#!/bin/bash

# [!] Do not rename this file to `bash_completion`
#     as it will create an infinite loop!

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

declare -r BASH_COMPLETION_PATH="$(brew --prefix 2> /dev/null)/etc/profile.d/bash_completion.sh"

if which brew &> /dev/null &&
   [ -r "$BASH_COMPLETION_PATH" ]; then

	# Ensure existing `bash-completion@1` continues to work.
    # https://github.com/Homebrew/homebrew-core/pull/36254

	export BASH_COMPLETION_COMPAT_DIR="$(brew --prefix)/etc/bash_completion.d"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Use the latest `bash-completion`.

	. "$BASH_COMPLETION_PATH"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Make Bash complete the `g` alias just like it does `git`.

    complete -o default -o nospace -F _git g

elif [ -f /etc/bash_completion ]; then
	source /etc/bash_completion;
fi
